### ISSUE TITLE
galvanized steel fence should have different collision box

### ISSUE THREAD

**Issue by AsumFace** [KaylebJay/tunnelers-bugz#16]
`infrastructure:fence_galvanized_steel` has the collision box of a solid node, the default fences and those of other modes have one matching the visual model more closely.

**Comment by KaylebJay** [comment]
Fixed @ https://gitlab.com/h2mm/roads/-/commit/867f697832addf61552a795a1311268084ab4b9b

**Comment by AsumFace** [comment]
i don't know about you but they still have the cubic box for me

**Comment by KaylebJay** [comment]
Looks like we never pulled it. :woozy_face:

**Comment by KaylebJay** [comment]
https://gitlab.com/h2mm/roads/-/commit/cd66362a8e7342c70aeb38699426f82eebc47b8a
fixed it a better way

**Comment by KaylebJay** [comment]
commit live
